ACCOUNTS = ["GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC"]
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
SIGNING_KEY = "GCGOC4BGGTMUPUF5QN25HYKAQ67LFFQLZGQP6MRNEPZ7BIQEWAPQWJGG"
WEB_AUTH_ENDPOINT = "https://api.etherfuse.com/stellar-auth"

[DOCUMENTATION]
ORG_NAME = "Etherfuse"
ORG_DBA = "Etherfuse"
ORG_URL = "https://etherfuse.com"
ORG_TWITTER = "etherfuse"
ORG_GITHUB = "etherfuse"

[[CURRENCIES]]
code = "USTRY"
issuer = "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC"
name = "Etherfuse USTRY"
desc = "Our US Treasury Notes Stablebond offers unparalleled security and peace of mind. Backed by the full faith and credit of the United States government, US Treasury Notes are among the safest investments available worldwide."
image = "https://stablebonds.s3.us-west-2.amazonaws.com/stablebond/spl-ustry.png"

[[CURRENCIES]]
code = "CETES"
issuer = "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC"
name = "Etherfuse CETES"
desc = "Etherfuse CETES, officially known as Certificados de la Tesorería de la Federación, are Mexico's oldest short-term debt securities issued by the Ministry of Finance."
image = "https://stablebonds.s3.us-west-2.amazonaws.com/stablebond/spl-cetes.png"

[[CURRENCIES]]
code = "TESOURO"
issuer = "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC"
name = "Etherfuse TESOURO"
desc = "Brazilian Tesouros are issued by the Brazilian government. As Brazil is the largest and most liquid economy in Latin and South America, these notes are widely considered as a low-risk investment."
image = "https://stablebonds.s3.us-west-2.amazonaws.com/stablebond/spl-tesouro.png"

[[CURRENCIES]]
code = "MEX"
issuer = "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC"
name = "Etherfuse MEX"
desc = "A special use token that will indefinitely stay at 0% APY"
image = "https://stablebonds.s3.us-west-2.amazonaws.com/stablebond/spl-mex.png"

[[CURRENCIES]]
code = "CETESZ"
issuer = "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC"
name = "Etherfuse CETES ZERO"
desc = "A special use CETES token that will indefinitely stay at 0% APY"
image = "https://stablebonds.s3.us-west-2.amazonaws.com/stablebond/spl-cetes0.png"
